#!/bin/bash

# -*- mode: sh -*-

PROGNAME="${0##*/}"

# Strip trailing '/'s
case ${1} in
    *[!/]*) BUILD_ROOT=${1%"${1##*[!/]}"};;
    *[/]) BUILD_ROOT="/";;
esac

if [ -z "${BUILD_ROOT}" ]; then
    printf -- "${PROGNAME}: Error: Undefined RTAGS_BUILD_ROOT (build root directory)\n" >&2
    exit 2
fi

RTAGS_BUILD_PATH="${BUILD_ROOT%*/}/.rtags"
RTAGS_SOCKET="rdm.socket"
RTAGS_LOG="rdm.log"

if [ -z "${YAUL_INSTALL_ROOT}" ]; then
    printf -- "${PROGNAME}: Error: Undefined YAUL_INSTALL_ROOT (install root directory)\n" >&2
    exit 2
fi

if ! command -v "rdm" >/dev/null; then
    printf -- "${PROGNAME}: Error: executable \`rdm' not found in \${PATH}\n" >&2
    exit 1
fi

if ! command -v "rc" >/dev/null; then
    printf -- "${PROGNAME}: Error: executable \`rc' not found in \${PATH}\n" >&2
    exit 1
fi

if [ -z "${YAUL_RTAGS}" ]; then
    printf -- "${PROGNAME}: Error: RTags support is disabled. Set \${YAUL_RTAGS} to \`true'\n" >&2
    exit 1
fi

mkdir -p "${RTAGS_BUILD_PATH}" >/dev/null 2>&1
mkdir -p "${RTAGS_BUILD_PATH%*/}/cache" >/dev/null 2>&1

if ! [ -d "${RTAGS_BUILD_PATH}" ]; then
    printf -- "${PROGNAME}: Error: RTags directory \`${RTAGS_BUILD_PATH}' cannot be created\n" >&2
    exit 1
fi

GCC_VERSION=`${YAUL_INSTALL_ROOT}/sh-elf/bin/sh-elf-gcc --version | awk '/^sh-elf-gcc/ { print $3 }'`

if [ -z "${GCC_VERSION}" ]; then
    printf -- "${PROGNAME}: Error: Cannot defer SH-2 GCC version\n" >&2
    exit 1
fi

# Kludge: Because our custom GCC specs file specifies the include
#         paths, Clang doesn't know about them:
#
#         The clang driver has no direct correspondent for
#         "specs". The best next solution is to manually include theme
#         here
exec rdm \
     --data-dir "${RTAGS_BUILD_PATH%*/}/cache" \
     --socket-file "${RTAGS_BUILD_PATH%*/}/${RTAGS_SOCKET}" \
     --log-file "${RTAGS_BUILD_PATH%*/}/${RTAGS_LOG}" \
     --silent \
     --log-file-log-level verbose-debug \
     --max-include-completion-depth 100 \
     --no-libclang-include-path \
     --isystem "${YAUL_INSTALL_ROOT}/sh-elf/lib/gcc/sh-elf/${GCC_VERSION}/include" \
     --include-path "${YAUL_INSTALL_ROOT}/sh-elf/sh-elf/include" \
     --include-path "${YAUL_INSTALL_ROOT}/sh-elf/sh-elf/include/bcl" \
     --include-path "${YAUL_INSTALL_ROOT}/sh-elf/sh-elf/include/tga" \
     --include-path "${YAUL_INSTALL_ROOT}/sh-elf/sh-elf/include/yaul" \
     --include-path "${YAUL_INSTALL_ROOT}/sh-elf/sh-elf/include/yaul/common" \
     --include-path "${YAUL_INSTALL_ROOT}/sh-elf/sh-elf/include/yaul/dbgio" \
     --include-path "${YAUL_INSTALL_ROOT}/sh-elf/sh-elf/include/yaul/math" \
     --include-path "${YAUL_INSTALL_ROOT}/sh-elf/sh-elf/include/yaul/lib" \
     --include-path "${YAUL_INSTALL_ROOT}/sh-elf/sh-elf/include/yaul/fs/iso9660" \
     --include-path "${YAUL_INSTALL_ROOT}/sh-elf/sh-elf/include/yaul/fs/romdisk" \
     --include-path "${YAUL_INSTALL_ROOT}/sh-elf/sh-elf/include/yaul/scu" \
     --include-path "${YAUL_INSTALL_ROOT}/sh-elf/sh-elf/include/yaul/scu/bus/a/cs0/arp" \
     --include-path "${YAUL_INSTALL_ROOT}/sh-elf/sh-elf/include/yaul/scu/bus/a/cs0/dram-cart" \
     --include-path "${YAUL_INSTALL_ROOT}/sh-elf/sh-elf/include/yaul/scu/bus/a/cs0/usb-cart" \
     --include-path "${YAUL_INSTALL_ROOT}/sh-elf/sh-elf/include/yaul/scu/bus/a/cs2/cd-block" \
     --include-path "${YAUL_INSTALL_ROOT}/sh-elf/sh-elf/include/yaul/scu/bus/b/scsp" \
     --include-path "${YAUL_INSTALL_ROOT}/sh-elf/sh-elf/include/yaul/scu/bus/b/vdp" \
     --include-path "${YAUL_INSTALL_ROOT}/sh-elf/sh-elf/include/yaul/scu/bus/cpu" \
     --include-path "${YAUL_INSTALL_ROOT}/sh-elf/sh-elf/include/yaul/scu/bus/cpu/smpc"
